### PR TITLE
Read parent pids from /proc/ instead of parsing pstree

### LINKED ISSUE #5: Doesn't work if sxhkd is run as a systemd service.
Hi!
I'm using sxhkd as a [systemd user service](https://github.com/baskerville/sxhkd/blob/master/contrib/systemd/sxhkd.service). I've made a small modification to the unit too (`KillMode=process`).

The thing is, this makes systemd the "parent" process. Running `pidswallow` with `verbose=1` on an Alacritty window gives this output:
```
systemd(724)---alacritty(25793)---zsh(25799)
```
Thus, the script doesn't work.
I tried messing around with the script for a bit, but I don't know much about process handling and the variable names just confused me more. So I gave up and made an issue.

Is there a way to work around this?

**Edit:** I'm honestly not sure if systemd has anything to do with it. I'm just assuming here (sorry if I'm wrong), since using a simpler `sxhkd &` inside bspwmrc doesn't cause any problems.

### PR DESCRIPTION
**Pull request by SeerLite**
It's a simple loop that reads the parent pids from the /proc/ filesystem until it reaches a swallowable. If no swallowable is found, the entire script exits.

Let me know what you think!

**Edit:** fixes #5

### CODE REVIEW

**Comment by SeerLite** [comment]
There's a lot more stuff I'd like to change in this script too (if you're ok with it!). 

For example, you used a lot of shell string manipulation to get the output of some commands, and I think it'd be more readable if `sed` and friends were used instead.

Expect more PRs in the future!

**Comment by Liupold** [comment]
Great work! I don't think `sed` is really necessary. Probably good comment will do for readability. (As speed is important). Remember each time a new node is created this script is executed.  

Another thing, if we use `proc/$cpid/status` we need to to use two external program, (Not bad, but it can be better if we use pstree). The behavior of your script is correct. I want to keep that. And this seems like i good way to do it. If a better way exist I might later change that. Thanks a lot for your contribution.

**Comment by SeerLite** [comment]
Hey! Thanks for merging!

I was just checking it out a little bit more and made these 2 last commits, and `verbose=1` slipped through! Sorry for that, I'm kind of new to adding stuff to github/git. I don't know how I should go about reverting that now that you merged (ironically I received this notification just as I was about to force-push to revert it)

About adding more processes to the execution, you may be right! I still want to do a bit more research about it though, cause there has to be a reason sed exists and is preferred over raw string manipulation (apart from readability of course)

**Comment by Liupold** [comment]
It's ok.(Will correct that) I don't have problem with that if the script is fast enough and behave correctly I will be more than happy to merge.

**Comment by SeerLite** [comment]
Great!

And oh, one last thing about this PR:
The README reads
> * launching a second term from dmenu will not be swallowed. (because it's runs as a zsh subprocess_
>   - Solution: `setsid -f kitty` instead of `kitty`. (from dmenu).

I'm not entirely sure if it's related to this, but can you check if by chance this merge fixed this too (so that no `setsid` workaround is needed)?

Thanks again

**Comment by Liupold** [comment]
WoW! Yes it's fixed. (As it's travels the whole tree).

**Comment by SeerLite** [comment]
That's great to hear!

Also, you may be right about the execution time being slower with this! I did some tests and realized that it's now 0.03s slower. This isn't too terrible, but still bad. I'm gonna mess around with it tomorrow and see if going back to `pstree` (still looping through its output in the same manner) is any better.

**Comment by Liupold** [comment]
Checkout the `dev` branch. It uses `pstree` and address the concern of this PR. (seems faster to me) 😀

**Pull request merged**
