### PR TITLE
Have loop exit on bspwm restart by reading report

### PR DESCRIPTION
**Pull request by SeerLite**
I hope you're ok with me just learning about git/github through this repo. Let me know if you think I'm doing anything wrong
This time, I'm making 2 small pull requests so you can check them out separately.

### CODE REVIEW

**Comment by SeerLite** [comment]
Oh, I forgot to say this before: I haven't run any benchmarks on this so I have no idea of it affects performance too much, so keep that in mind before any merging.

**Comment by Liupold** [comment]
This seems like a much neater alternative. Does it work? (After restarting I mean). If so then there should be very less performance issue. We need to make sure the script exits when `Xorg/bspwm` is killed, when not running as it's children. Say using `setsid -f` or `disown`. I believe the script will exit because of `bspc`. (As `bspc`'s socket will be closed).

**Comment by SeerLite** [comment]
Yeah, so far it's worked fine for me! Once a restart is detected the loop returns/breaks, so as it's fine to just re-run the script from bspwmrc again. Also, yeah I'm pretty sure `bspc subscribe` exits when its `bspwm` counterpart exits.

I was worried about the performance because the `while` loop now receives a lot more lines thanks to `bspc subscribe report`, but now I'm _pretty_ sure it's fine. It's just some basic string checks, after all.

**Comment by Liupold** [comment]
Ya, it fine coinciding it's just some shell syntax (no external calls). Need to do some testing before merge. (Just to make sure everything works).

**Pull request merged**
