### PR TITLE
dev: Better support for specific WMs through user defined environment variables

### PR DESCRIPTION
**Pull request by SeerLite**
More info in each commit message and also in the README. Let me know what you think!

I'm not sure if using `eval` on an environment variable is considered a good practice, but I wanted to keep it simple. Feel free to reject it/modify the implementation if you think it's bad!

### CODE REVIEW

**Comment by SeerLite** [comment]
Ok, this is funny but now after rebasing a lot and then making the PR, it's suddenly not working for me anymore hehe. Give me some time to see what's up

**Comment by SeerLite** [comment]
Nevermind, it's not the script itself it's just the examples (which I'm also using in my own config). Fixing it now

**Comment by SeerLite** [comment]
There's some more issues I didn't see while testing and I'd like to fix them before merging.

**Edit:** All good now. And of course, test it out by yourself first!

**Comment by Liupold** [comment]
Hey, instead of `(eval "$cmd")`, how about `$("$cmd")`.

https://github.com/Liupold/pidswallow/pull/19/commits/2fd81656cbf8f6b20d72eb4b132c3ae3e1dcdd36
* I don't think this will help during toggle. (You can't quickly toggle again).
* Moreover if suppose some thing in playing in mpv on desktop 1, and  i am working on dekstop 2
if that had finished playing i will surprisingly jump to desktop 1. (Not intended)

https://github.com/Liupold/pidswallow/pull/19/commits/25762fb3be2e341f126b18754bfb8ec2d0b1ace9
* I think we should use a patter (Eg: `{%cpid}`). (And use sed to expand).
* Don't rely on expanding. (Shell is already pretty complicated).

**Comment by SeerLite** [comment]
> Hey, instead of (eval "$cmd"), how about $("$cmd").

I actually tried that before going with `eval`. It wouldn't work because the shell thinks the whole string is the command/executable and gives a `command not found`

> * I don't think this will help during toggle. (You can't quickly toggle again).
> 
> * Moreover if suppose some thing in playing in mpv on desktop 1, and  i am working on dekstop 2
>   if that had finished playing i will surprisingly jump to desktop 1. (Not intended)

I didn't think of this! Good points! The reason I did this originally was because `xdotool set_desktop_for_window` completely messed up the layout of the desktop if the window it was moving wasn't focused. I'm gonna have to look into that tomorrow.

> * I think we should use a patter (Eg: `{%cpid}`). (And use sed to expand).
> 
> * Don't rely on expanding. (Shell is already pretty complicated).

This was my idea originally, but then I noticed that expanding was a simple enough solution and went with that instead. The only thing we have to keep in mind is to always have `$pwid` and `$cwid` set before `eval`ing.

The `sed` idea isn't too bad though. I could give it a try tomorrow (or you could do so in the meantime if you feel like it)

**Comment by SeerLite** [comment]
image
The `>/dev/null` won't get parsed as shell expression. Looks like we're gonna have to use `eval` either way :/

**Comment by Liupold** [comment]
Ya, eval is the only way it seems, changing that.

**Comment by SeerLite** [comment]
Hehe. I'm not sure about the `sed` implementation now though.
Since we're already using `eval` again, `$cwid` and `$pwid` work too.

Edit: Or instead of `eval` we can pipe the command to a subshell? Give me a sec to test that out

**Comment by Liupold** [comment]
Ok, seems interesting, I don't want to change sed, it's a bit of safety. Suppose if the cmd is 
```
unset pwid # or something more subtle 
pwid=1 # like this, it will be problematic 
```
using eval is a bit risky. (Even a typo can crash the script). This can still happen.
using `{%pwid}` is just a bit safer.  (in my opinion)

the time of the script (toggle mode, whole script execution) is around `0.06`, seems good to me.
(it will be faster in `--loop` mode)

**Comment by SeerLite** [comment]
> Ok, seems interesting, I don't want to change sed, it's a bit of safety. Suppose if the cmd is
> 
> ```
> unset pwid # or something more subtle 
> pwid=1 # like this, it will be problematic 
> ```
> 
> using eval is a bit risky. (Even a typo can crash the script). This can still happen.
> using `{%pwid}` is just a bit safer. (in my opinion)

Wait, doesn't the subshell negate this? That's exactly the reason I put the evals in a subshell each

**Comment by Liupold** [comment]
I am stupid....
```
rohnch:~/$ test=1022                                                               [11:36:58]
rohnch:~/$ echo "$test"                                                            [11:37:01]
1022
rohnch:~/$ (eval 'unset test')                                                     [11:37:02]
rohnch:~/$ echo "$test"                                                            [11:37:11]
1022
rohnch:~/$ eval 'unset test'                                                       [11:37:13]
rohnch:~/$ echo "$test"                                                            [11:37:18]

rohnch:~/$                                                                         [11:37:19]

```
adding sub shell. Thanks i didn't knew that. (Reverting back to your last commit).

**Comment by SeerLite** [comment]
[piping_patch.txt](https://github.com/Liupold/pidswallow/files/4999127/piping_patch.txt)
~~GitHub not supporting different file extensions is driving me crazy~~
This is what I was messing around with. Pretty new to using patches so I hope I did it right

Edit: IMO going back to `eval` inside subshells is the best way to do this. But then again, don't trust me with that haha
Edit: nvm you're doing that now lol

**Comment by SeerLite** [comment]
> I am stupid....

Don't worry about it ;) I learned it today too when I was trying to fix the exact problem you were thinking of

**Comment by Liupold** [comment]
why so?
Using the patch might be better. internal vars won't be leaked.
I am confused. What do you suggest.

**Comment by SeerLite** [comment]
> internal vars won't be leaked.

They won't? If they don't then yeah the patch is the way

**Comment by SeerLite** [comment]
Just tested it. Yup the patch is the way

**Comment by Liupold** [comment]
patching...

**Comment by SeerLite** [comment]
I was just about to tell you swallowing didn't work and that I thought I messed up somewhere. Sorry about that!

**Comment by Liupold** [comment]
No it did. I messed up, sorry for that.

**Comment by Liupold** [comment]
Everything is working. (hopefully) give it a try. BTW, do you have any system or know someone with plasma installed. (I can't get plasma to work on my laptop. already had 5 WM installed) 😂.

**Comment by SeerLite** [comment]
Yeah it's working! Maybe not relevant but: I still have some issues with stuff I don't want to "glue", maybe a "glue_blacklist" is a good idea?

I'll see if I can get Plasma installed for tomorrow (it's pretty late rn for me). I'll see if I can get some other DEs installed too, I'll let you know how it goes!

**Comment by Liupold** [comment]
Thanks a lot, I am inviting you as a collaborator.

**Comment by SeerLite** [comment]
Oh that's really cool! Thank you so much! Even though it may seem simple because this is just a small script for a small feature, I've learned a lot through this, so I appreciate it!

**Comment by Liupold** [comment]
Same here. Honestly it was simple not anymore. Thanks a lot for yr awesome job. Good night.

**Comment by Liupold** [comment]
I am merging this. (Its already 20+ commits behind).

**Pull request merged**
