### PR TITLE
AUR

### PR DESCRIPTION
**Pull request by Liupold**
AUR PKGBUILD and supporting workflow.

### CODE REVIEW

**Comment by Liupold** [comment]
Don't merge yet.!

**Comment by SeerLite** [comment]
Woow now this is some interesting stuff. I'm not touching any of this though because I don't understand it and not in the mood to learn it either lol

**Comment by Liupold** [comment]
The only thing left to do is to automate the release. (So that it will be updated on each release). Need some time. Expect 1-2 days. You can work on the man though.

**Comment by SeerLite** [comment]
Oo hey I have no clue how to write man pages though! Besides, I'd like to focus more on the functionality of the script before anything like that.
I think it's fine to just leave it at the `--help` flag, at least for now.
What do you think?

**Comment by Liupold** [comment]
Okay I will Handel the documentation. No prob.

**Comment by Liupold** [comment]
Merging now(A lot of commit), The workflow (release hook) will be add later.

**Pull request merged**
