### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by SeerLite**
More info on the commit messages

### CODE REVIEW

**Comment by SeerLite** [comment]
Latest commit is about what I was thinking [here](https://github.com/Liupold/pidswallow/issues/8#issuecomment-657125546)

**Comment by Liupold** [comment]
Looks really good, thanks for this awesome job.

**Comment by Liupold** [comment]
https://github.com/Liupold/pidswallow/pull/9/commits/4a69df285bb3c4bd769f8a85e7ae9a485305521b seems to solve the complain with `pstree`. The script is looking real good, We can merge with main soon.

The only thing lacking is demo. This script can do so much more now. Do you want to update the demo ?

**Comment by SeerLite** [comment]
Yeah, I think `pstree` is reliable enough (for now at least) so I'm gonna close #8 .

As for the demo, I'm not sure I want to be the one doing it hehe. My setup is a little messy right now and I'd rather not record my screen (even if it's for 10 seconds).
Also, I think the current one is fine as it is. It demonstrates the main feature of the script, which is what most people come for. Although it wouldn't be a bad idea to update the demo it to a GIF so it can be embedded in the README page, instead of having to click the youtube link.

**Pull request merged**
