### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Liupold**
Improvements:

* CLI like flags support
* loop is now build in
* `pstree` parsing is much more stable thanks to [SeerLite](https://github.com/SeerLite)
* pipe support.
* Typo fixed.
* Super simple to use and install.

### CODE REVIEW

**Comment by Liupold** [comment]
This should fix #2 .

**Comment by Liupold** [comment]
> Did it mess up the performance too much or do you think this method is better?
 

I didn't know it was executing on each even (my poor testing). It wasn't slow but on a laptop its counts (specialty on battery). Moreover I this is much more effective as someone might accidentally run `pidswallow --loop` twice. This is just simply not possible now. What do you think?

**Comment by SeerLite** [comment]
> > Did it mess up the performance too much or do you think this method is better?
> 
> I didn't know it was executing on each even (my poor testing). It wasn't slow but on a laptop its counts (specialty on battery). Moreover I this is much more effective as someone might accidentally run `pidswallow --loop` twice. This is just simply not possible now. What do you think?

Oh I completely missed this reply haha, sorry! Good thing we figured out doesn't use too many resources.
I also did some quick tests by monitoring `htop` now, and I think it's all fine. The only way the script could start causing problems is if there's lots of constant window/wm/xorg activity, and at that point I'm sure it's gonna be Xorg or even bspwm using more resources than our little script heh

IMO it's all ready to be merged now!

**Comment by Liupold** [comment]
Merged, thanks a lot for all that awesome job.

**Pull request merged**
